import sys
import subprocess
import os
import argparse
import setup.test_config as test_config 
import unittest

def main():
    # Fetch the command line arguments
    parser = argparse.ArgumentParser(description='Run test suite with a specific date.')
    parser.add_argument('--date', type=str, default='20230831', help='Date of the test data (e.g., 20231231).')
    args = parser.parse_args()

    try:
        test_config.main(["--date", args.date])
    except ValueError as e:
        print(f"Error: {e}")
        sys.exit(1)

   # Discover and run unit tests
    print("Running unit tests...")
    unit_tests = unittest.TestLoader().discover('mig_mtrxs/unit')
    unittest.TextTestRunner(verbosity=2).run(unit_tests)

    # Discover and run integration tests
    print("Running integration tests...")
    integration_tests = unittest.TestLoader().discover('mig_mtrxs/integration')
    unittest.TextTestRunner(verbosity=2).run(integration_tests)

if __name__ == '__main__':
    main()



IST_plus_v0.01) [sandbox jf42370@dsq/rmo-sandbox tests] (master)$ python3 run_tests.py --date 20230831
Environment variable TEST_DATE set to 20230831
Running unit tests...
test_extract_mig_mtrxs (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_extract_mig_mtrxs (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_extract_mig_mtrxs
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/conda/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/jovyan/IST_plus_v0.01/tests/mig_mtrxs/unit/test_extract_mig_mtrxs.py", line 9, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'



